
graph TB
    A[音节] --> |当音节无介音时|B[无介音节]
    A --> |当音节有介音时|C[有介音节]

    B --> |提取|D[节调]
    B --> |提取|E[节质]

    C --> |提取|F[节调]
    C --> |提取|G[节质]

    D --> H[节调]
    E --> |切分|I[声母]
    E --> |切分|J[无介韵母]

    F --> K[节调]
    G --> |切分|L[声母]
    G --> |切分|M[有介韵母]

