graph TB
    A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    C --> |切分|D[介质]
    C --> |切分|E[韵质（韵基）]
    D --> |改名|F[韵头]
    E --> |切分|G[韵腹]
    E --> |切分|H[韵尾]
    F --> |改名|I[呼质]
    G --> |改名|J[主质]
    H --> |改名|L[末质]
    B --> |切分|M[呼调]
    B --> |切分|N[韵调]
    N -->  |切分|O[主调]
    N -->  |切分|P[末调]
    O -->  |传递|Q[主调]
    P -->  |传递|R[末调]
    M --> |传递|S[呼调]
    S --> |传递|T[呼调]
    T -->  |构成|U[呼音]
    I -->  |构成|U
    Q -->  |构成|V[主音]
    J -->  |构成|V
    R -->  |构成|W[末音]
    L -->  |构成|W
    U -->  |构成|X[干音]
    V -->  |构成|X
    W -->  |构成|X
