graph BT

O[ɤ] --- OU(ɤᴜ)
U[ᴜ] --- OU(ɤᴜ)

OU ---  B(●)
B ---  B1[5]

OU ---  C(●)
C ---  C1[3]
C ---  C2[5]

OU ---  D(●)
D ---  D1[2]
D --- D2[1]
D --- D3[4]

OU ---  E(●)
E ---  E1[5]
E --- E2[1]

classDef plain fill:none,stroke:none:font-size:64px;
class O,U,OU,B,C,D,E,B1,C1,C2,D1,D2,D3,E1,E2,Title plain;

