graph TB
    A[干音]
    A --> |提取|B[干调]
    B --> |传递|B1[干调]
    B1 --> |切分|B2[间调]
    B1 --> |切分|B3[末调]
    B2 -->  |切分|B4[呼调]
    B2 -->  |切分|B5[主调]
    B3 -->  |传递|B6[末调]
    B4 -->  |传递|B7[呼调]
    B5 -->  |传递|B8[主调]
    B6 -->  |传递|B9[末调]

    A --> |提取|C[韵母]
    C --> |又分析为|D[韵基]
    D --> |切分|E[间质（韵腹）]
    D --> |切分|F[韵尾]
    E --> |切分|G[间质前段]
    E --> |切分|H[间质后段]
    G --> |改名|I[呼质]
    H --> |改名|J[主质]
    F -->  |传递|K[韵尾]
    K --> |改名|L[末质]

    B7 -->  |构成|M[呼音]
    I -->  |构成|M
    B8 -->  |构成|N[主音]
    J -->  |构成|N
    B9 -->  |构成|O[末音]
    L -->  |构成|O
    M -->  |构成|P[干音]
    N -->  |构成|P
    O -->  |构成|P
