graph TB
    A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]
    B --> |传递|B1[干调]
    B1 --> |切分|B2[呼调]
    B1 --> |切分|B3[主调]
    B1 --> |切分|B4[末调]
    B2 --> |传递|K[呼调]
    B3 --> |传递|L[主调]
    B4 --> |传递|M[末调]
    C --> |又分析为|D[韵腹]
    D --> |切分|E[韵母前段]
    D --> |切分|F[韵母中段]
    D --> |切分|G[韵母后段]
    E --> |改名|H[呼质]
    F --> |改名|I[主质]
    G --> |改名|J[末质]
    K -->  |构成|N[呼音]
    H -->  |构成|N
    L -->  |构成|O[主音]
    I -->  |构成|O
    M -->  |构成|P[末音]
    J -->  |构成|P
    N -->  |构成|Q[干音]
    O -->  |构成|Q
    P -->  |构成|Q
