graph TB
    A[干音]
    A --> |提取|B[干调]
    A --> |提取|C[韵母]

    B --> |切分|D1[呼调]
    B --> |切分|D2[韵调]
    D1 --> |传递|D3[呼调]
    D2 --> |传递|D4[韵调]
    D3 --> |传递|D5[呼调]
    D4 --> |切分|D6[主调]
    D4 --> |切分|D7[末调]
    D5 --> |传递|D8[呼调]
    D6 -->  |传递|P[主调]
    D7 -->  |传递|Q[末调]

    C --> |切分|E[介质]
    C --> |切分|F[韵质（韵基）]

    E --> |又分析为|G[韵头]
    G --> |传递|H[韵头]
    H --> |改名|I[呼质]

    F --> |又分析为|J[韵腹（韵身）]
    J --> |切分|K[韵质前段]
    J --> |切分|L[韵质后段]
    K --> |改名|M[主质]
    L --> |改名|N[末质]

    D8 --> |构成|O[呼音]
    I --> |构成|O
    P -->  |构成|R[主音]
    M -->  |构成|R
    Q -->  |构成|S[末音]
    N -->  |构成|S
    O -->  |构成|T[干音]
    R -->  |构成|T
    S -->  |构成|T
