graph TB
    A[音节]
        A --> |提取音节的音调|B[节调<br>声调]
        A --> |提取音节的音质|C[节质<br>由声母与韵母构成的音质]

        B --> |切分首音的音调<br>提取与声母联结的调段|D1[首调]
        B --> |切分干音的音调<br>提取与韵母联结的调段|D2[干调]
        C --> |提取首音的音质<br>切分声母|E1[首质]
        C --> |提取干音的音质<br>切分韵母|E2[干质]

        D1 --> |构成|F[首音]
        E1 --> |构成|F
        D2 --> |构成|G[干音]
        E2 --> |构成|G

        F --> |分类| F1[实首音]
        F --> |分类| F2[虚首音]
        F1 --> |提取| H1[非零声母]
        F2 --> |提取| H2[零声母]
        F1 --> |提取| H3[首调]
        F2 --> |提取| H4[首调]

        H3 ---> |统称| H5
        H4 ---> |统称| H5[首调]
        H1 ---> |统称| H6
        H2 ---> |统称| H6[声母]
        H5 --> |构成| H9
        H6 --> |构成| H9[首音]

        G --> |分类|G1[单质干音]
        G --> |分类|G2[后长干音]
        G --> |分类|G3[前长干音]
        G --> |分类|G4[三质干音]

        G1 --> |提取|J1[干调]
        J1 --> J2[干调]
        J2 --> J3[干调]
        G1 --> |提取|J4[单质韵母]
        J4 --> |又分析为|J5[韵基]
        J5 --> |又分析为|J6[韵腹]

        G2 --> |提取|K0[干调]
        K0 --> |切分|K1[呼调]
        K0 --> |切分|K2[韵调]
        G2 --> |提取|K3[后长韵母]
        K1 --> K7[呼调]
        K2 --> K8[韵调]
        K3 --> |切分|K9[介质]
        K3 --> |切分|K5[韵基]
        K9 --> |改名|K4[韵头]
        K5 --> |又分析为|K6[韵腹]

        G3 --> |提取|L0[干调]
        G3 --> |提取|L4[前长韵母]
        L0 --> L1[干调]
        L1 --> |切分|L2[间调]
        L1 --> |切分|L3[末调]
        L4 --> |又分析为|L5[韵基]
        L5 --> |切分|L6[韵腹]
        L5 --> |切分|L7[韵尾]

        G4 --> |提取|M0[干调]
        M0 --> |切分|M01[呼调]
        M0 --> |切分|M02[韵调]
        M01 --> M1[呼调]
        M02 --> |切分|M2[主调]
        M02 --> |切分|M3[末调]
        G4 --> |提取|M4[三质韵母]
        M4 --> |切分|M5[介质]
        M4 --> |切分|M6[韵基]
        M5 --> |改名|M7[韵头]
        M6 --> |切分|M8[韵腹]
        M6 --> |切分|M9[韵尾]

        J3 --> |构成|N1[干音]
        J6 --> |构成|N1

        K7 --> |构成|O1[介音]
        K4 --> |构成|O1
        K8 --> |构成|O2[韵音]
        K6 --> |构成|O2

        L2 --> |构成|P1[间音]
        L6 --> |构成|P1
        L3 --> |构成|P2[尾音]
        L7 --> |构成|P2

        M1 --> |构成|Q1[介音]
        M7 --> |构成|Q1
        M2 --> |构成|Q2[主音]
        M8 --> |构成|Q2
        M3 --> |构成|Q3[尾音]
        M9 --> |构成|Q3

        H9 --> R0[首音]
        R0 --> R1[首音]

        N1 --> |充当|R2[单质干音]

        O1 --> |构成|R3
        O2 --> |构成|R3[后长干音]

        P1 --> |构成|R4
        P2 --> |构成|R4[前长干音]

        Q1 --> |构成|R5
        Q2 --> |构成|R5
        Q3 --> |构成|R5[三质干音]

        R2  --> |统称|R6[干音]
        R3  --> |统称|R6
        R4  --> |统称|R6
        R5  --> |统称|R6

        R1 --> |构成|S
        R6 --> |构成|S[音节]
