graph TB
    A[音节] --> |切分|B[首音干音]
    B --> |分析|C[声——调<br>声母韵母]

    C --> |分类|E[声————调<br>声母无介韵母]
    C --> |分类|F[声————调<br>声母有介韵母]

    E -->  |分析|G[声——————调<br>声母韵————腹]
    E -->  |分析|H[声——————调<br>声母韵——腹韵尾]
    F -->  |分析|I[声——————调<br>声母韵头韵——腹]
    F -->  |分析|J[声——————调<br>声母韵头韵腹韵尾]

    G ---> |从第一类音节中切分|G1[首音]
    H ---> |从第二类音节中切分|G1[首音]
    I ---> |从第三类音节中切分|G1[首音]
    J ---> |从第四类音节中切分|G1[首音]

    G ---> |从第一类音节中切分|G2[呼音]
    H ---> |从第二类音节中切分|G2[呼音]
    I ---> |从第三类音节中切分|G2[呼音]
    J ---> |从第四类音节中切分|G2[呼音]

    G ---> |从第一类音节中切分|G3[主音]
    H ---> |从第二类音节中切分|G3[主音]
    I ---> |从第三类音节中切分|G3[主音]
    J ---> |从第四类音节中切分|G3[主音]

    G ---> |从第一类音节中切分|G4[末音]
    H ---> |从第二类音节中切分|G4[末音]
    I ---> |从第三类音节中切分|G4[末音]
    J ---> |从第四类音节中切分|G4[末音]


