graph TB
A[节质]  --- B1[声母单质韵母型节质]
A --- B2[声母前长韵母型节质]
A --- B3[声母后长韵母型节质]
A --- B4[声母三质韵母型节质]
B1 ---- C1[声母]
B1 ---- C2[韵腹]
B2 ---- D1[声母]
B2 ---- D2[韵腹]
B2 ---- D3[韵尾]
B3 ---- E1[声母]
B3 ---- E2[韵头]
B3 ---- E3[韵腹]
B4 ---- F1[声母]
B4 ---- F2[韵头]
B4 ---- F3[韵腹]
B4 ---- F4[韵尾]
