graph TB
A[节质]  --- B1[声母单质韵母型节质]
A --- B2[声母前长韵母型节质]
A --- B3[声母后长韵母型节质]
A --- B4[声母三质韵母型节质]

B1 ----- C1[声母]
B1 --- C2[韵母]
C2 --- C3[韵基]
C3 --- C4[韵腹]

B2 ----- D1[声母]
B2 --- D2[韵母]
D2 --- D3[韵基]
D3 --- D4[韵腹]
D3 --- D5[韵尾]

B3 ----- E1[声母]
B3 --- E2[韵母]
E2 ---- E3[韵头]
E2 --- E4[韵基]
E4 --- E5[韵腹]

B4 ----- F1[声母]
B4 --- F2[韵母]
F2 ---- F3[韵头]
F2 --- F4[韵基]
F4 --- F5[韵腹]
F4 --- F6[韵尾]

