graph TB
    A[音节] --> |提取|B[节调]
    A --> |提取|C[节质]
    C --> |切分|D[声母]
    C --> |切分|E[韵母]
    E --> |是否韵质|F{判断}
    F --> |是|G[干韵韵母]
    G --> |又分析为|H[韵质]
    F --> |否|I[介韵韵母]
    I --> |切分|J[介质]
    I --> |切分|K[韵质]
    H --> |是否单质|H0{?}
    H0 --> |是|L[单质韵质]
    H0 --> |否|M[复合韵质]
    K --> |是否单质|K0{?}
    K0 --> |是|N[单质韵质]
    K0 --> |否|O[复合韵质]
    J --> |传递|U[介质]
    J --> |传递|V[介质]
    subgraph 单质韵母[单质韵母]
    L --> |又分析为|P[韵腹]
    end
    subgraph 后长韵母[后长韵母]
    M --> |切分|Q[韵腹]
    M --> |切分|R[韵尾]
    end
    subgraph 前长韵母[前长韵母]
    V --> |又分析为|S[韵头]
    N --> |又分析为|T[韵腹]
    end
    subgraph 三质韵母[三质韵母]
    U --> |又分析为|W[韵头]
    O --> |切分|X[韵腹]
    O --> |切分|Y[韵尾]
    end

