graph TB
    A[音节] ---> |当韵母是单质韵母时|A1[单干音节]
    A[音节] ---> |当韵母是前长韵母时|A2[单间音节]
    A[音节] ---> |当韵母是后长韵母时|A3[单韵音节]
    A[音节] ---> |当韵母是三质韵母时|A4[四质音节]

    A1 ---> |提取|B1[节调]
    A2 ---> |提取|B2[节调]
    A3 ---> |提取|B3[节调]
    A4 ---> |提取|B4[节调]


    A1 ---> |提取|C1[节质]
    A2 ---> |提取|C2[节质]
    A3 ---> |提取|C3[节质]
    A4 ---> |提取|C4[节质]

    C1 --> |切分|D1[声母]
    C2 --> |切分|D2[声母]
    C3 --> |切分|D3[声母]
    C4 --> |切分|D4[声母]

    C1 --> |切分|E1[韵母]
    C2 --> |切分|E2[韵母]
    C3 --> |切分|E3[韵母]
    C4 --> |切分|E4[韵母]

    B1 --> F1[节调]
    F1 --> F2[节调]
    F2 --> F3[节调]
    D1 --> |改名|F4[首质]
    F4 --> |恢复原名|F5[声母]
    E1 --> |又分析为|F6[韵质]
    F6 --> |又分析为|F7[韵腹]

    B2 --> G1[节调]
    G1 --> G2[节调]
    G2 --> G3[节调]
    D2 --> |改名|G4[首质]
    G4 --> |恢复原名|G5[声母]
    E2 --> |又分析为|G6[韵质]
    G6 --> |切分|G7[韵腹]
    G6 --> |切分|G8[韵尾]

    B3 --> H1[节调]
    H1 --> H2[节调]
    H2 --> H3[节调]
    D3 --> |改名|H4[首质]
    H4 --> |恢复原名|H5[声母]
    E3 --> |切分|H6[介质]
    E3 --> |切分|H7[韵质]
    H6 --> |又分析为|H8[韵头]
    H7 --> |又分析为|H9[韵腹]

    B4 --> I0[节调]
    I0 --> I1[节调]
    I1 --> I2[节调]
    D4 --> |改名|I3[首质]
    I3 --> |恢复原名|I4[声母]
    E4 --> |切分|I5[介质]
    E4 --> |切分|I6[韵质]
    I5 --> |切分|I7[韵头]
    I6 --> |切分|I8[韵腹]
    I6 --> |切分|I9[韵尾]
