graph TB
    A[音节] ---> B[节——————调<br>声母韵————腹]
    A ---> C[节——————调<br>声母韵头韵——腹]
    A ---> D[节——————调<br>声母韵——腹韵尾]
    A ---> E[节——————调<br>声母韵头韵腹韵尾]

    B ---> |从第一类音节中切分|F[首音]
    C ---> |从第二类音节中切分| F[首音]
    D ---> |从第三类音节中切分| F[首音]
    E ---> |从第四类音节中切分| F[首音]

    B ---> |从第一类音节中切分|G[呼音]
    C ---> |从第二类音节中切分| G[呼音]
    D ---> |从第三类音节中切分| G[呼音]
    E ---> |从第四类音节中切分| G[呼音]

    B ---> |从第一类音节中切分| H[主音]
    C ---> |从第二类音节中切分| H[主音]
    D ---> |从第三类音节中切分| H[主音]
    E ---> |从第四类音节中切分| H[主音]

    B ---> |从第一类音节中切分| I[末音]
    C ---> |从第二类音节中切分| I[末音]
    D ---> |从第三类音节中切分| I[末音]
    E ---> |从第四类音节中切分| I[末音]
