graph TB
    A[节————调<br>声母韵——腹]
    B[节——————调<br>声母韵头韵——腹]
    C[节——————调<br>声母韵——腹韵尾]
    D[节——————调<br>声母韵头韵腹韵尾]

    A --> |提取|A1[首调<br>声母]
    A --> |提取|A2[呼调<br>韵母前段]
    A --> |提取|A3[主调<br>韵母中段]
    A --> |提取|A4[末调<br>韵母后段]

    subgraph 单干音节[ ]
    A1 --> A5[首调<br>首质]
    A2 --> A6[呼调<br>呼质]
    A3 --> A7[主调<br>主质]
    A4 --> A8[末调<br>末质]
    end

    B --> |提取|B1[首调<br>声母]
    B --> |提取|B2[呼调<br>韵头]
    B --> |提取|B3[主调<br>韵质前段]
    B --> |提取|B4[末调<br>韵质后段]

    B1 --> B5[首调<br>首质]
    B2 --> B6[呼调<br>呼质]
    B3 --> B7[主调<br>主质]
    B4 --> B8[末调<br>末质]

    C --> |提取|C1[首调<br>声母]
    C --> |提取|C2[呼调<br>间质前段]
    C --> |提取|C3[主调<br>间质后段]
    C --> |提取|C4[末调<br>韵尾]

    C1 --> C5[首调<br>首质]
    C2 --> C6[呼调<br>呼质]
    C3 --> C7[主调<br>主质]
    C4 --> C8[末调<br>末质]

    D --> |提取|D1[首调<br>声母]
    D --> |提取|D2[呼调<br>韵头]
    D --> |提取|D3[主调<br>韵腹]
    D --> |提取|D4[末调<br>韵尾]

    subgraph 四合音节[ ]
    D1 --> D5[首调<br>首质]
    D2 --> D6[呼调<br>呼质]
    D3 --> D7[主调<br>主质]
    D4 --> D8[末调<br>末质]
    end

    A5 ---> |构成首音|F[首音]
    B5 ---> |构成首音|F[首音]
    C5 ---> |构成首音|F[首音]
    D5 ---> |构成首音|F[首音]

    A6 ---> |构成呼音|G[呼音]
    B6 ---> |构成呼音|G[呼音]
    C6 ---> |构成呼音|G[呼音]
    D6 ---> |构成呼音|G[呼音]

    A7 ---> |构成主音|H[主音]
    B7 ---> |构成主音|H[主音]
    C7 ---> |构成主音|H[主音]
    D7 ---> |构成主音|H[主音]

    A8 ---> |构成末音|I[末音]
    B8 ---> |构成末音|I[末音]
    C8 ---> |构成末音|I[末音]
    D8 ---> |构成末音|I[末音]



