graph TB
        A[音节] --> |提取音节的音调|B[节调<br>声调]
        A --> |提取音节的音质|C[节质<br>由声母与韵母构成的音质]

        B --> |切分首音的音调<br>提取与声母联结的调段|D1[首调]
        B --> |切分干音的音调<br>提取与韵母联结的调段|D2[干调]
        C --> |提取首音的音质<br>切分声母|E1[首质]
        C --> |提取干音的音质<br>切分韵母|E2[干质]

        D1 --> |构成|F[首音]
        E1 --> |构成|F
        D2 --> |构成|G[干音]
        E2 --> |构成|G

        F --> |分类|F1[实首音]
        F --> |分类|F2[虚首音]
        F1 --> |提取| F3[首调]
        F1 --> |提取| F4[非零声母]
        F2 --> |提取| F5[首调]
        F2 --> |提取| F6[零声母]

        F3 --> |统称| H1
        F5 --> |统称| H1[首调]
        F4 --> |统称| H2
        F6 --> |统称| H2[声母]
        H1 --->  H5[首调]
        H2 ---> |改名| H6[首质]
        H5 --> |构成|H7
        H6 --> |构成|H7[噪音]

        G --> |分类|G1[三质干音]
        G --> |分类|G2[前长干音]
        G --> |分类|G3[后长干音]
        G --> |分类|G4[单质干音]

        G4 --> |提取|J1[干调]
        J1 ----> |切分|J2[呼调]
        J1 ----> |切分|J3[主调]
        J1 ----> |切分|J4[末调]
        G4 --> |提取|J5[单质韵母]
        J5 ---> |切分|J61[韵母前段]
        J5 ---> |切分|J62[韵母中段]
        J5 ---> |切分|J63[韵母后段]

        G3 --> |提取|K1[干调]
        K1 --> |切分|K2[呼调]
        K1 --> |切分|K3[韵调]
        K3 ---> |切分|K31[主调]
        K3 ---> |切分|K32[末调]
        K2 ---> K33[呼调]
        G3 --> |提取|K4[后长韵母]
        K4 --> |切分|K5[介质]
        K4 --> |切分|K6[韵质（韵基）]
        K5 --> |改名|K51[韵头]
        K6 --> |切分|K61[韵质前段]
        K6 --> |切分|K62[韵质后段]

        G2 --> |提取|L0[干调]
        L0 --> |切分|L1[间调]
        L0 --> |切分|L2[末调]
        L1 ---> |切分|L11[呼调]
        L1 ---> |切分|L12[主调]
        L2 ---> L33[末调]
        G2 --> |提取|L4[前长韵母]
        L4 --> |切分|L5[间质（韵腹）]
        L4 --> |切分|L6[韵尾]
        L5 --> |切分|L51[间质前段]
        L5 --> |切分|L52[间质后段]
        L6 --> L61[韵尾]

        G1 --> |提取|M0[干调]
        M0 --> |切分|M1[呼调]
        M0 --> |切分|M2[韵调]
        M1 ---> M3[呼调]
        M2 ---> |切分|M21[主调]
        M2 ---> |切分|M22[末调]
        G1 --> |提取|M4[三质韵母]
        M4 --> |切分|M5[介质]
        M4 --> |切分|M6[韵质（韵基）]
        M5 --> |改名|M51[韵头]
        M6 --> |切分|M61[韵腹]
        M6 --> |切分|M62[韵尾]

        J61 --> |改名|J7[呼质]
        J62 --> |改名|J8[主质]
        J63 --> |改名|J9[末质]
        K51 --> |改名|K7[呼质]
        K61 --> |改名|K8[主质]
        K62 --> |改名|K9[末质]
        L51 --> |改名|L7[呼质]
        L52 --> |改名|L8[主质]
        L61 --> |改名|L9[末质]
        M51 --> |改名|M7[呼质]
        M61 --> |改名|M8[主质]
        M62 --> |改名|M9[末质]

        J2 --> |构成|N1[乐音]
        J7 --> |构成|N1
        J3 --> |构成|N2[乐音]
        J8 --> |构成|N2
        J4 --> |构成|N3[乐音]
        J9 --> |构成|N3

        K33 --> |构成|O1[乐音]
        K7 --> |构成|O1
        K31 --> |构成|O2[乐音]
        K8 --> |构成|O2
        K32 --> |构成|O3[乐音]
        K9 --> |构成|O3

        L11 --> |构成|P1[乐音]
        L7 --> |构成|P1
        L12 --> |构成|P2[乐音]
        L8 --> |构成|P2
        L33 --> |构成|P3[乐音]
        L9 --> |构成|P3

        M3 --> |构成|P4[乐音]
        M7 --> |构成|P4
        M21 --> |构成|P5[乐音]
        M8 --> |构成|P5
        M22 --> |构成|P6[乐音]
        M9 --> |构成|P6

        H7 --> |充当首音|Q[首音]
        N1 --> |充当呼音|R[呼音]
        N2 --> |充当主音|S[主音]
        N3 --> |充当末音|T[末音]

        O1 --> |充当呼音|R
        O2 --> |充当主音|S
        O3 --> |充当末音|T

        P1 --> |充当呼音|R
        P2 --> |充当主音|S
        P3 --> |充当末音|T

        P4 --> |充当呼音|R
        P5 --> |充当主音|S
        P6 --> |充当末音|T

        Q --> U[首音]
        R --> V[呼音]
        S --> |构成|W[韵音]
        T --> |构成|W

        U --> X[首音]
        V --> |构成|Y[干音]
        W --> |构成|Y

        X --> |构成|Z[音节]
        Y --> |构成|Z
